=== h0gar/Bytewalla/assets/dtn.config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.bytewalla.tslab.ssvl.kth.se/DTNConf" xmlns:tns="http://www.bytewalla.tslab.ssvl.kth.se/DTNConf" elementFormDefault="qualified">


    <complexType name="DTNConfiguration">
    	<all>
    		<element name="StorageSetting" type="tns:StorageSetting"></element>
    		<element name="InterfacesSetting"
    			type="tns:InterfacesSetting">
    		</element>
    		<element name="LinksSetting" type="tns:LinksSetting"></element>
    		<element name="RoutesSetting" type="tns:RoutesSetting"></element>
    		<element name="DiscoveriesSetting" type="tns:DiscoveriesSetting"></element>
    	</all>
    </complexType>

    <element name="DTNConfiguration" type="tns:DTNConfiguration"></element>


    <complexType name="StorageSetting">
    	<attribute name="type" use="required">
    		<simpleType>
    			<restriction base="string">
    				<enumeration value="phone"></enumeration>
    				<enumeration value="sdcard"></enumeration>
    			</restriction>
    		</simpleType>
    	</attribute>
    	<attribute name="quota" type="int">
    		<annotation>
    			<documentation>
    				Storage Quota setting (MB)
    			</documentation>
    		</annotation>
    	</attribute>
    	<attribute name="storage_path" type="string"></attribute>
    </complexType>

    <complexType name="Interface">
    	<attribute name="id" type="string" use="required"></attribute>
    	<attribute name="local_port" type="int" use="optional"></attribute>
    	<attribute name="conv_layer_type">
    	
    		<simpleType>
    			<restriction base="string">
    				<enumeration value="tcp"></enumeration>
    			</restriction>
    		</simpleType>
    	</attribute>
    </complexType>



    <complexType name="InterfacesSetting">
    	<sequence>
    		<element name="Interface" type="tns:Interface" minOccurs="0"
    			maxOccurs="unbounded">
    		</element>
    	</sequence>
    </complexType>

    <complexType name="Link">
    	<attribute name="id" type="string" use="required"></attribute>
    	<attribute name="dest" type="string"></attribute>
    	<attribute name="type">
    		<simpleType>
    			<restriction base="string">
    				<enumeration value="ALWAYSON"></enumeration>
    				<enumeration value="ONDEMAND"></enumeration>
    				<enumeration value="SCHEDULED"></enumeration>
    				<enumeration value="OPPORTUNISTIC"></enumeration>
    			</restriction>
    		</simpleType>
    	</attribute>
    	<attribute name="conv_layer_type">
    		<simpleType>
    			<restriction base="string">
    				<enumeration value="tcp"></enumeration>
    			</restriction>
    		</simpleType>
    	</attribute>
    </complexType>

    <complexType name="LinksSetting">
    	<sequence>
    		<element name="Link" type="tns:Link" minOccurs="0"
    			maxOccurs="unbounded"></element>
    	</sequence>
    </complexType>

    <complexType name="Route">
    	<attribute name="dest" type="string" use="required"></attribute>
    	<attribute name="link_id" type="string"></attribute>
    </complexType>
    
    <complexType name="RoutesSetting">
    	<sequence>
    		<element name="Route" type="tns:Route" minOccurs="0"
    			maxOccurs="unbounded">
    		</element>
    	</sequence>
    	<attribute name="router_type" use="required">
    		<simpleType>
    			<restriction base="string">
    				<enumeration value="static"></enumeration>
    				<enumeration value="prophet"></enumeration>
    			</restriction>
    		</simpleType>
    	</attribute>
    	<attribute name="local_eid" type="string"></attribute>
    	
	    	<attribute name="P_encounter" type="float"></attribute>
    		<attribute name="P_encounter_first" type="float"></attribute>
    		<attribute name="P_encounter" type="float"></attribute>
    		<attribute name="alpha" type="float"></attribute>
    		<attribute name="beta" type="float"></attribute>
    		<attribute name="delta" type="float"></attribute>
    		<attribute name="K" type="int"></attribute>
 	
    </complexType>
    

    <complexType name="Discovery">
    	<attribute name="id" type="string" use="required"></attribute>
    	<attribute name="address_family">
    		<simpleType>
    			<restriction base="string">
    				<enumeration value="ip"></enumeration>
    			</restriction>
    		</simpleType>
    	</attribute>
    	<attribute name="port" type="int"></attribute>
    </complexType>

    <complexType name="DiscoveriesSetting">
    	<sequence>
    		<element name="Discovery" type="tns:Discovery" maxOccurs="unbounded" minOccurs="0"></element>
    		<element name="Announce" type="tns:Announce" maxOccurs="unbounded" minOccurs="0"></element>
    	</sequence>
    </complexType>

    <complexType name="Announce">
    	<attribute name="interface_id" type="string" use="required"></attribute>
    	<attribute name="discovery_id" type="string"></attribute>
    	<attribute name="conv_layer_type" type="string"></attribute>
    	<attribute name="interval" type="int" use="optional"></attribute>
    </complexType>
</schema>

=== h0gar/Bytewalla/assets/dtn.config.xml
<?xml version="1.0" encoding="UTF-8"?>

	<!--  Main configuration file for Android DTN Project -->
	<!--  Its XML Schema is dtn.config.xsd in the same folder -->
<tns:DTNConfiguration xmlns:tns="http://www.bytewalla.tslab.ssvl.kth.se/DTNConf"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.bytewalla.tslab.ssvl.kth.se/DTNConf dtn.config.xsd">

	<!--  Storage Section -->
	<!--  Setup your storage here -->
	<!--  type can be phone or sdcard -->
	<!--
		quota is the space you will allow DTN to store bundles in the storage
		type you set, the unit is Megabytes
	-->
	<tns:StorageSetting type="sdcard" quota="300"
		storage_path="dtn" />


	<!--  Interfaces Section -->
	<tns:InterfacesSetting>
		<!--  Setup your listening interfaces here -->
		<tns:Interface id="tcp0" conv_layer_type="tcp"
			local_port="4556" />
	</tns:InterfacesSetting>


	<!--  Links Section -->
	<tns:LinksSetting>
		<!--  Setup your links here -->
	</tns:LinksSetting>


	<!--  Routes Section -->
	<tns:RoutesSetting router_type="prophet" P_encounter="0.5"
		P_encounter_first="0.25" delta="0.01" alpha="0.5" beta="0.9" K="1">
		<!--  Setup your routes here -->
	</tns:RoutesSetting>

	<tns:DiscoveriesSetting>
		<!--  Setup your Discovery here -->
		<tns:Discovery id="ipdisc0" address_family="ip" port="9556"></tns:Discovery>
		<tns:Announce interface_id="tcp0" discovery_id="ipdisc0"
			conv_layer_type="tcp"></tns:Announce>
	</tns:DiscoveriesSetting>

</tns:DTNConfiguration>
